### ISSUE TITLE
Results are 16 chars long

### ISSUE THREAD

**Issue by rowland** [imdario/go-ulid#1]
```
Titan:extract brent$ cat test_ulid.go
package main

import (
	"fmt"

	"github.com/imdario/go-ulid"
)

func main() {
	fmt.Println(ulid.New().String())
}
Titan:extract brent$ go run test_ulid.go
01BG6TRR41VB7RJY
```

**Comment by darccio** [comment]
I was planning to "sunset" this repository. Please, check these forks that are currently maintained:

* https://github.com/hlian/dilaudid
* https://github.com/oklog/ulid

**Comment by rowland** [comment]
Ok. I switched to oklog/ulid.

I think there were null bytes in the output.
